#!/bin/bash
export PATH=$PATH


__string_contain() { case $2 in *$1* ) return 0;; *) return 1;; esac ;}


__is_interactive=false
__call_print() {
    echo "$@"
    local call=true
    if [ "$__is_interactive" = "true" ]; then
        echo "Confirm [Y/n]"
        read __confirm
        if [ "$__confirm" = "n" ] || [ "$__confirm" = "N" ]; then
            call=false
        fi
    fi
    if [ "$call" = "true" ]; then
        ("$@")
    fi
}


__parse_args(){
    local cli_args=("editor" "template_debug" "template_release" "mono" "executable" "static" "shared" "suffix" "arch" "platform")
    while :; do
        local matched=false
        local variable="$1"
        for arg in ${cli_args[@]}; do
            if [ "${variable%=*}" = "$arg" ]; then
                matched=true
                local value="${variable#*=}"
                if ! __string_contain "=" "$variable" || [ -z "$value" ]; then
                    value=true
                fi
                declare -g "arg_${arg}=$value"
                shift
                break
            fi
        done
        if [ "$matched" = false ]; then
            break
        fi
    done

    arg_rest=("$@")
}


__parse_godot_args() {
    local local_suffix=""
    __parse_args "$@"

    arg_executable=true
    type_args="library_type=executable"
    local_suffix="executable"
    if [ "$arg_static" = true ]; then
        arg_executable=false
        type_args="library_type=static_library"
        local_suffix="static"
    elif [ "$arg_shared" = true ]; then
        arg_executable=false
        type_args="library_type=shared_library"
        local_suffix="shared"
    fi

    if [ "$arg_mono" = true ]; then
        mono_args="module_mono_enabled=yes"
    fi

    type_args="${type_args} extra_suffix=${local_suffix}"

    if [ -n "$arg_platform" ]; then
        type_args="platform=$arg_platform $type_args"
    fi

    if __string_contain "llvm" "$arg_suffix"; then
        type_args="$type_args linker=lld use_llvm=yes"
    fi

    if [ "$arg_platform" = "web" ]; then
        type_args="$type_args import_env_vars=EMSDK"
    fi
    
}


__build_godot_editor() {
    __call_print scons target=editor $type_args production=yes debug_symbols=yes compiledb=yes disable_path_overrides=no $mono_args ${arg_rest[@]}
    if [ "$arg_executable" = true ] && [ -n "$mono_args" ]; then
        __call_print find ./bin -name "godot.*.editor.*executable.mono*" -type f -exec {} --generate-mono-glue ./modules/mono/glue --headless ';'
        __call_print ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir ./bin --push-nupkgs-local ./../.nuget_local/
    fi
}
__build_godot_template_debug() {
    __call_print scons target=template_debug $type_args production=yes debug_symbols=yes compiledb=yes disable_path_overrides=no $mono_args ${arg_rest[@]}
}
__build_godot_template_release() {
    __call_print scons target=template_release $type_args production=yes compiledb=yes disable_path_overrides=no $mono_args ${arg_rest[@]}
}


__build_godot() {
    cd ./godot
    local built=false
    __parse_godot_args "$@"

    if [ "$arg_editor" = true ]; then
        __build_godot_editor
        built=true
    fi
    if [ "$arg_template_debug" = true ]; then
        __build_godot_template_debug
        built=true
    fi
    if [ "$arg_template_release" = true ]; then
        __build_godot_template_release
        built=true
    fi

    if [ "$built" = false ]; then
        __build_godot_editor
        __build_godot_template_debug
        __build_godot_template_release
    fi
    cd ./..
}


__parse_cpp_args() {
    __parse_args "$@"

    godot_type="static"
    if [ "$arg_static" = true ]; then
        godot_type="static"
    elif [ "$arg_shared" = true ]; then
        godot_type="shared"
    fi

    if [ -z "$arg_platform" ]; then
        echo "Must specify "platform=" for C++"
        exit 1
    fi

    godot_platform="$arg_platform"

    if [ -z "$arg_arch" ]; then
        arg_arch="x86_64"
    fi

    if [ "$godot_platform" = "web" ]; then
        arg_arch="wasm32"
    fi

    if [ -n "$arg_suffix" ]; then
        arg_suffix="-DEXTRA_SUFFIX="$arg_suffix""
    fi
}


__build_cpp_generic() {
    export CMAKE_GENERATOR="Ninja"
    local web_args=""
    if [ "$godot_platform" = "web" ]; then
        web_args="--toolchain=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_PROJECT_INCLUDE:FILEPATH=../godot-cpp/cmake/emsdkHack.cmake"
    elif __string_contain "llvm" "$arg_suffix"; then
        export CC="clang"
        export CXX="clang++"
    fi
    __call_print cmake -S . -B "build/$godot_platform/$1_$godot_type" -DCMAKE_BUILD_TYPE=GodotConfig -DGODOT_TARGET="$1" -DGODOT_PLATFORM=$godot_platform -DGODOT_TYPE=$godot_type -DGODOT_ARCH=$arg_arch $arg_suffix $web_args ${arg_rest[@]}
    __call_print cmake --build "build/$godot_platform/$1_$godot_type"
}


__build_cpp() {
    cd ./cpp_project
    local built=false
    __parse_cpp_args "$@"

    if [ "$arg_editor" = true ]; then
        __build_cpp_generic editor
        built=true
    fi
    if [ "$arg_template_debug" = true ]; then
        __build_cpp_generic template_debug
        built=true
    fi
    if [ "$arg_template_release" = true ]; then
        __build_cpp_generic template_release
        built=true
    fi

    if [ "$built" = false ]; then
        __build_cpp_generic editor
        __build_cpp_generic template_debug
        __build_cpp_generic template_release
    fi
    cd ./..
}

__parse_csharp_args() {
    __parse_args "$@"

    godot_type="static"
    if [ "$arg_static" = true ]; then
        godot_type="static"
    elif [ "$arg_shared" = true ]; then
        godot_type="shared"
    fi

    godot_platform="$arg_platform"

    if [ -z "$arg_arch" ]; then
        arg_arch="x86_64"
    fi

    platform_args=""
    if [ "$godot_platform" = "linuxbsd" ]; then
        platform_args="-r linux-x64"
    elif [ "$godot_platform" = "windows" ]; then
        platform_args="-r win-x64"
    elif [ "$godot_platform" = "macos" ]; then
        platform_args="-r osx-x64"
    elif [ "$godot_platform" = "web" ]; then
        platform_args="-r browser-wasm"
        arg_arch="wasm32"
    fi

    if [ -n "$arg_suffix" ]; then
        arg_suffix="-p:ExtraSuffix=$arg_suffix"
    fi
}


__build_csharp_generic() {
    __call_print dotnet build
    __call_print dotnet publish -v:d -c "$1" $platform_args -p:GodotType="$godot_type" -p:GodotArch="$arg_arch" $arg_suffix ${arg_rest[@]}
}


__build_csharp() {
    cd ./csharp_project
    local built=false
    __parse_csharp_args "$@"

    if [ "$arg_editor" = true ]; then
        __build_csharp_generic Debug
        built=true
    fi
    if [ "$arg_template_debug" = true ]; then
        __build_csharp_generic ExportDebug
        built=true
    fi
    if [ "$arg_template_release" = true ]; then
        __build_csharp_generic ExportRelease
        built=true
    fi

    if [ "$built" = false ]; then
        __build_csharp_generic Debug
        __build_csharp_generic ExportDebug
        __build_csharp_generic ExportRelease
    fi
    cd ./..
}


build() {
    if [ "$1" = "godot" ]; then
        __build_godot "${@:2}"
    elif [ "$1" = "cpp" ]; then
        __build_cpp "${@:2}"
    elif [ "$1" = "csharp" ]; then
        __build_csharp "${@:2}"
    else
        echo "No target"
    fi
}


__run_cpp() {
    cd ./cpp_project
    __parse_cpp_args "$@"
    if ! ls -d ./templates/$godot_platform/editor_$godot_type/editor > /dev/null; then
        __build_cpp_generic editor
    fi
    __call_print ./templates/$godot_platform/editor_$godot_type/editor 
    cd ./..
}


__run_csharp() {
    cd ./csharp_project
    __parse_csharp_args "$@"
    __call_print dotnet run -c Debug $platform_args -p:GodotType=shared -p:GodotArch="$arg_arch" $arg_suffix ${arg_rest[@]}
    cd ./..
}


start() {
    if [ "$1" = "cpp" ]; then
        __run_cpp "${@:2}"
    elif [ "$1" = "csharp" ]; then
        __run_csharp "${@:2}"
    else
        echo "No target"
    fi
}


print_help() {
    echo "Available commands:"
    echo "  bash run build godot [editor] [template_debug] [template_release] [executable|static|shared] [mono] [platform=(linuxbsd|windows|macos|web)] [scons args]"
    echo "  bash run build cpp [editor] [template_debug] [template_release] [static|shared] [suffix=*] [arch=*] platform=(linuxbsd|windows|macos|web) [cmake configure args]"
    echo "  bash run build csharp [editor] [template_debug] [template_release] [static|shared] [suffix=*] [arch=*] [platform=(linuxbsd|windows|macos|web)] [msbuild args]"
    echo "  bash run start cpp [suffix=*] [arch=*] platform=(linuxbsd|windows|macos|web) [cmake configure args]"
    echo "  bash run start csharp [suffix=*] [arch=*] [platform=(linuxbsd|windows|macos|web)] [msbuild args]"
    echo ""
    echo "Commands inside [] are optional, arguments with '=' expect value, '*' is any value"
    echo ""
    echo "Available modifiers:"
    echo "  bash run -i [command]: will enable interactive mode, you can choose if you want to lauch the command"
}


__handle_cmdline_args() {
    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        print_help
        return 0
    fi
    if  [ "$1" = "-i" ]; then
        __is_interactive=true
        shift
    fi

    __cmdline_rest="($@)"
    return 1
}


if ! __handle_cmdline_args "$@"; then
    eval "$__cmdline_rest"
fi 
